import React from "react";

// Copyright-aware mock data - using generic placeholder names and local avatars
export const users = [
  {
    id: 1,
    name: "Player Alpha",
    role: "Team Captain",
    team: "Vanguard",
    status: "active",
    age: "29",
    avatar: "/avatars/default-1.svg",
    email: "player.alpha@example.com",
  },
  {
    id: 2,
    name: "Player Bravo",
    role: "IGL",
    team: "Phoenix",
    status: "paused",
    age: "25",
    avatar: "/avatars/default-2.svg",
    email: "player.bravo@example.com",
  },
  {
    id: 3,
    name: "Player Charlie",
    role: "Entry Fragger",
    team: "Phoenix",
    status: "active",
    age: "22",
    avatar: "/avatars/default-3.svg",
    email: "player.charlie@example.com",
  },
  {
    id: 4,
    name: "Player Delta",
    role: "AWPer",
    team: "Titan",
    status: "vacation",
    age: "28",
    avatar: "/avatars/default-4.svg",
    email: "player.delta@example.com",
  },
  {
    id: 5,
    name: "Player Echo",
    role: "Support",
    team: "Sentinel",
    status: "active",
    age: "24",
    avatar: "/avatars/default-5.svg",
    email: "player.echo@example.com",
  },
  {
    id: 6,
    name: "Player Foxtrot",
    role: "Lurker",
    team: "Vanguard",
    age: "29",
    avatar: "/avatars/default-6.svg",
    email: "player.foxtrot@example.com",
    status: "Active",
  },
  {
    id: 7,
    name: "Player Golf",
    role: "Rifler",
    team: "Apex",
    status: "paused",
    age: "27",
    avatar: "/avatars/default-7.svg",
    email: "player.golf@example.com",
  },
  {
    id: 8,
    name: "Player Hotel",
    role: "Coach",
    team: "Storm",
    status: "active",
    age: "31",
    avatar: "/avatars/default-8.svg",
    email: "player.hotel@example.com",
  },
  {
    id: 9,
    name: "Player India",
    role: "Analyst",
    team: "Zenith",
    status: "vacation",
    age: "33",
    avatar: "/avatars/default-9.svg",
    email: "player.india@example.com",
  },
  {
    id: 10,
    name: "Player Juliet",
    role: "Manager",
    team: "Eclipse",
    status: "active",
    age: "35",
    avatar: "/avatars/default-10.svg",
    email: "player.juliet@example.com",
  },
  {
    id: 11,
    name: "Player Kilo",
    role: "Entry Fragger",
    team: "Phoenix",
    status: "active",
    age: "22",
    avatar: "/avatars/default-11.svg",
    email: "player.kilo@example.com",
  },
  {
    id: 12,
    name: "Player Lima",
    role: "IGL",
    team: "Titan",
    status: "paused",
    age: "28",
    avatar: "/avatars/default-12.svg",
    email: "player.lima@example.com",
  },
  {
    id: 13,
    name: "Player Mike",
    role: "AWPer",
    team: "Sentinel",
    status: "active",
    age: "37",
    avatar: "/avatars/default-1.svg",
    email: "player.mike@example.com",
  },
  {
    id: 14,
    name: "Player November",
    role: "Support",
    team: "Titan",
    status: "active",
    age: "30",
    avatar: "/avatars/default-2.svg",
    email: "player.november@example.com",
  },
  {
    id: 15,
    name: "Player Oscar",
    role: "Lurker",
    team: "Storm",
    status: "paused",
    age: "31",
    avatar: "/avatars/default-3.svg",
    email: "player.oscar@example.com",
  },
  {
    id: 16,
    name: "Player Papa",
    role: "Rifler",
    team: "Sentinel",
    status: "active",
    age: "29",
    avatar: "/avatars/default-4.svg",
    email: "player.papa@example.com",
  },
  {
    id: 17,
    name: "Player Quebec",
    role: "Analyst",
    team: "Apex",
    status: "active",
    age: "28",
    avatar: "/avatars/default-5.svg",
    email: "player.quebec@example.com",
  },
  {
    id: 18,
    name: "Player Romeo",
    role: "Coach",
    team: "Zenith",
    status: "active",
    age: "27",
    avatar: "/avatars/default-6.svg",
    email: "player.romeo@example.com",
  },
  {
    id: 19,
    name: "Player Sierra",
    role: "Manager",
    team: "Eclipse",
    status: "paused",
    age: "32",
    avatar: "/avatars/default-7.svg",
    email: "player.sierra@example.com",
  },
  {
    id: 20,
    name: "Player Tango",
    role: "Team Captain",
    team: "Vanguard",
    status: "active",
    age: "26",
    avatar: "/avatars/default-8.svg",
    email: "player.tango@example.com",
  },
];
