import { GameEventClutchSituationIcon, GameEventPistolRoundIcon } from "@/components/icons";
import React from "react";

export const enum GameEventCategoryOption {
    All = "all",
    ClutchSituation = "ClutchSituation",
    EcoSituation = "EcoSituation", // can start in a round, and finish in another round (until full buy or force buy)
    PistolRound = "PistolRound", // only first round
    AntiEco = "AntiEco",
    FullBuy = "FullBuy",
    HalfBuy = "HalfBuy",
    ForceBuy = "ForceBuy",
    SpikePlant = "SpikePlant",
    Defuse = "Defuse",
    Trade = "Trade",
    EntryFrag = "EntryFrag",
    ExitFrag = "ExitFrag",
    Boost = "Boost",
    Wallbang = "Wallbang",
    KnifeFight = "KnifeFight",
    Utility = "Utility",
    Positioning = "Positioning",
    Communication = "Communication",
    Aim = "Aim",
    TeamPlay = "TeamPlay",
    Economy = "Economy",
    Strategy = "Strategy",
    CounterStrategy = "CounterStrategy",
    AntiStrat = "AntiStrat",
    MapKnowledge = "MapKnowledge",
    Equipment = "Equipment",
    GameSense = "GameSense",
    Timing = "Timing",
    Pressure = "Pressure",
    Adaptability = "Adaptability",
    DecisionMaking = "DecisionMaking",
    Consistency = "Consistency",
    Reflexes = "Reflexes",
    AimDuel = "AimDuel",
    AimTraining = "AimTraining",
    AimControl = "AimControl",
    AimFlick = "AimFlick",
    AimPrecision = "AimPrecision",
    AimRecoilControl = "AimRecoilControl",
    AimCrosshairPlacement = "AimCrosshairPlacement",
    AimPeek = "AimPeek",
    AimMovement = "AimMovement",
    AimShootingTechnique = "AimShootingTechnique",
    AimWarmup = "AimWarmup",

    // AIM TRAINING
    // AimWorkshopMap = "AimWorkshopMap",
    // AimTrainingRoutine = "AimTrainingRoutine",
    // AimTrainingSchedule = "AimTrainingSchedule",
    // AimTrainingMethod = "AimTrainingMethod",
    // AimTrainingGoal = "AimTrainingGoal",
    // AimTrainingFeedback = "AimTrainingFeedback",
    // AimTrainingProgress = "AimTrainingProgress",
    // AimTrainingAchievement = "AimTrainingAchievement",
    // AimTrainingReward = "AimTrainingReward",
    // AimTrainingRecord = "AimTrainingRecord",
    // AimTrainingRanking = "AimTrainingRanking",
    // AimTrainingLeaderboard = "AimTrainingLeaderboard",
    // AimTrainingComparison = "AimTrainingComparison",
    // AimTrainingAnalysis = "AimTrainingAnalysis",
    // AimTrainingReview = "AimTrainingReview",
    // AimTrainingRecommendation = "AimTrainingRecommendation",
    // AimTrainingImprovement = "AimTrainingImprovement",
    // AimTrainingOptimization = "AimTrainingOptimization",
    // AimTrainingCustomization = "AimTrainingCustomization",
    // AimTrainingPersonalization = "AimTrainingPersonalization",
    // AimTrainingSpecialization = "AimTrainingSpecialization",

}

// const enum GameEventTypeOption {
//     ClutchStart = "custom::clutch_start",
//     ClutchProgress = "custom::clutch_progress",
//     ClutchEnd = "custom:clutch_end",
//     EcoStart = "EcoStart", // can start in a round, and finish in another round (until full buy or force buy)
//     EcoEnd = "EcoEnd",
//     PistolRoundStart = "PistolRoundStart", // only first round
//     PistolRoundEnd = "PistolRoundEnd", // only first round
//     AntiEcoStart = "AntiEcoStart",
//     AntiEcoEnd = "AntiEcoEnd",
//     FullBuyStart = "FullBuyStart",
//     FullBuyEnd = "FullBuyEnd",
//     HalfBuyStart = "HalfBuyStart",
//     HalfBuyEnd = "HalfBuyEnd",
//     ForceBuyStart = "ForceBuyStart",
//     ForceBuyEnd = "ForceBuyEnd",
//     SpikePlantStart = "SpikePlantStart",
//     SpikePlantEnd = "SpikePlantEnd",
//     DefuseStart = "DefuseStart",
//     DefuseEnd = "DefuseEnd",
//     TradeStart = "TradeStart",
//     TradeEnd = "TradeEnd",
//     EntryFragStart = "EntryFragStart",
//     EntryFragEnd = "EntryFragEnd",
//     ExitFragStart = "ExitFragStart",
//     ExitFragEnd = "ExitFragEnd",
//     BoostStart = "BoostStart",
//     BoostEnd = "BoostEnd",
//     WallbangStart = "WallbangStart",
//     WallbangEnd = "WallbangEnd",
//     KnifeFightStart = "KnifeFightStart",
//     KnifeFightProgress = "KnifeFightProgress",
//     KnifeFightEnd = "KnifeFightEnd",
//     UtilityStart = "UtilityStart",
//     UtilityEnd = "UtilityEnd",
//     PositioningStart = "PositioningStart",
//     PositioningEnd = "PositioningEnd",
//     CommunicationStart = "CommunicationStart",
//     CommunicationEnd = "CommunicationEnd",
//     AimStart = "AimStart",
//     AimEnd = "AimEnd",
//     TeamPlayStart = "TeamPlayStart",
//     TeamPlayEnd = "TeamPlayEnd",
//     EconomyStart = "EconomyStart",
//     EconomyEnd = "EconomyEnd",
//     StrategyStart = "StrategyStart",
//     StrategyEnd = "StrategyEnd",
//     CounterStrategyStart = "CounterStrategyStart",
//     CounterStrategyEnd = "CounterStrategyEnd",
//     AntiStratStart = "AntiStratStart",
//     AntiStratEnd = "AntiStratEnd",
//     MapKnowledgeStart = "MapKnowledgeStart",
//     MapKnowledgeEnd = "MapKnowledgeEnd",
//     EquipmentStart = "EquipmentStart",
//     EquipmentEnd = "EquipmentEnd",
//     GameSenseStart = "GameSenseStart",
//     GameSenseEnd = "GameSenseEnd",
//     TimingStart = "TimingStart",
//     TimingEnd = "TimingEnd",
//     PressureStart = "PressureStart",
//     PressureEnd = "PressureEnd",
//     AdaptabilityStart = "AdaptabilityStart",
//     AdaptabilityEnd = "AdaptabilityEnd",
//     DecisionMakingStart = "DecisionMakingStart",
//     DecisionMakingEnd = "DecisionMakingEnd",
//     ConsistencyStart = "ConsistencyStart",
//     ConsistencyEnd = "ConsistencyEnd",
//     ReflexesStart = "ReflexesStart",
//     ReflexesEnd = "ReflexesEnd",
//     AimDuelStart = "AimDuelStart",
//     AimDuelEnd = "AimDuelEnd",
//     AimTrainingStart = "AimTrainingStart",
//     AimTrainingEnd = "AimTrainingEnd",
//     AimControlStart = "AimControlStart",
//     AimControlEnd = "AimControlEnd",
//     AimFlickStart = "AimFlickStart",
//     AimFlickEnd = "AimFlickEnd",
//     AimPrecisionStart = "AimPrecisionStart",
//     AimPrecisionEnd = "AimPrecisionEnd",
//     AimRecoilControlStart = "AimRecoilControlStart",
//     AimRecoilControlEnd = "AimRecoilControlEnd",
//     AimCrosshairPlacementStart = "AimCrosshairPlacementStart",
//     AimCrosshairPlacementEnd = "AimCrosshairPlacementEnd",
//     AimPeekStart = "AimPeekStart",
//     AimPeekEnd = "AimPeekEnd",
//     AimMovementStart = "AimMovementStart",
//     AimMovementEnd = "AimMovementEnd",
//     AimShootingTechniqueStart = "AimShootingTechniqueStart",
//     AimShootingTechniqueEnd = "AimShootingTechniqueEnd",
//     AimWarmupStart = "AimWarmupStart",
//     AimWarmupEnd = "AimWarmupEnd",
// }

const enum ClutchStatusOptions {
    NotInClutchSituation = "not_in_clutch_situation",
	ClutchInitiated = "clutch_initiated",
	ClutchProgress  = "clutch_progress",
	ClutchLost      = "clutch_lost",
	ClutchWon       = "clutch_won",
}

const ClutchStatusDescription: Record<ClutchStatusOptions, string> = {
    [ClutchStatusOptions.NotInClutchSituation]: "Not Clutching",
    [ClutchStatusOptions.ClutchInitiated]: "Clutch Initiated",
    [ClutchStatusOptions.ClutchProgress]: "Clutch Progress",
    [ClutchStatusOptions.ClutchLost]: "Clutch Lost",
    [ClutchStatusOptions.ClutchWon]: "Clutch Won",
}

const enum PistolRoundStatusOptions {
    PistolRoundNotPistolRound = "not_pistol_round",
    PistolRoundInitiated = "pistol_round_initiated",
    PistolRoundProgress = "pistol_round_progress",
    PistolRoundEnded = "pistol_round_ended",
}

const PistolRoundStatusDescription: Record<PistolRoundStatusOptions, string> = {
    [PistolRoundStatusOptions.PistolRoundNotPistolRound]: "Not Pistol Round",
    [PistolRoundStatusOptions.PistolRoundInitiated]: "Pistol Round Initiated",
    [PistolRoundStatusOptions.PistolRoundProgress]: "Pistol Round Progress",
    [PistolRoundStatusOptions.PistolRoundEnded]: "Pistol Round Ended",
}

export const GameEventVariationsMap = {
    [GameEventCategoryOption.ClutchSituation]: {
        icon: (props: any) => <GameEventClutchSituationIcon {...props} />,
        description: "Clutch Situation",
        emptySelectionPlaceholder: "Any Clutch Situation",
        variations: ["1v2", "1v3", "1v4", "1v5"],
        values: ClutchStatusDescription,
    },
    [GameEventCategoryOption.PistolRound]: {
        icon: (props: any) => <GameEventPistolRoundIcon {...props} />,
        description: "Pistol Round",
        emptySelectionPlaceholder: "All Pistol Rounds",
        variations: ["1st-half", "2nd-half", "Overtime"], // TODO: add/check for overtime rounds
        values: PistolRoundStatusDescription,
    },
    [GameEventCategoryOption.Aim]: {
        icon: null,
        description: "Aim",
        emptySelectionPlaceholder: "Any Aim Event",
        variations: ["AimFlick", "AimDuel", "AimTraining", "AimControl", "AimPrecision", "AimRecoilControl", "AimCrosshairPlacement", "AimPeek", "AimMovement", "AimShootingTechnique", "AimWarmup"],
        values: ["Start", "Progress", "End"],
    },
    [GameEventCategoryOption.Utility]: {
        icon: null,
        description: "Utility",
        emptySelectionPlaceholder: "All Utility Events",
        variations: ["Smoke", "Molotov", "Flash", "HE", "Decoy"],
        values: ["Pixel", "One-way", "Combo", "Fake", "Retake", "Post-plant", "Pre-plant", "Counter"],
    },
    [GameEventCategoryOption.Positioning]: {
        icon: null,
        description: "Positioning",
        emptySelectionPlaceholder: "All Positioning Events",
        variations: ["Rotating", "Peeking", "CrosshairPlacement", "Positioning", "Holding"],
        values: ["Start", "Progress", "End"],
    },
    [GameEventCategoryOption.Communication]: {
        icon: null,
        description: "Communication",
        emptySelectionPlaceholder: "Any Communication Event",
        variations: ["Callout", "Comms", "TeamChat", "VoiceChat", "TextChat"],
        // values: ["Start", "Progress", "End"],
    },
    [GameEventCategoryOption.TeamPlay]: {
        icon: null,
        description: "Team Play",
        emptySelectionPlaceholder: "Any Team Play Event",
        variations: ["TeamPlay", "Trade", "Boost", "Flash", "Smoke", "Molotov", "HE", "Decoy"],
        // values: ["Start", "Progress", "End"],
    },
    [GameEventCategoryOption.Economy]: {
        icon: null,
        description: "Economy",
        emptySelectionPlaceholder: "Any Economy Event",
        variations: ["FullBuy", "HalfBuy", "ForceBuy", "Eco", "AntiEco"],
        values: ["Start", "End"], // "Progress", talvez pode ser utilizado para marcar quando ganhou, mas não necessariamente quer dizer que terminou. o player pode continuar em eco
    },
    [GameEventCategoryOption.Strategy]: {
        icon: null,
        description: "Strategy",
        emptySelectionPlaceholder: "Any Strategy Event",
        variations: ["MapKnowledge", "Strategy", "CounterStrategy", "AntiStrat"],
        values: ["Start", "Progress", "End"], // "Progress",: talvez possa ser utilizado quando: "CounterStrategy" -> "Progress" -> "End", ou quando fragar, ou conseguir entrar no site etc, ganhar,
    },
    [GameEventCategoryOption.Equipment]: {
        icon: null,
        description: "Equipment",
        emptySelectionPlaceholder: "Any Equipment Event",
        variations: ["Equip", "Unequip", "Buy", "Sell", "Upgrade", "Downgrade", "Trade"],
    },
    [GameEventCategoryOption.GameSense]: {
        icon: null,
        description: "Game Sense",
        emptySelectionPlaceholder: "Any GameSense Event",
        variations: ["Pressure", "DecisionMaking", "GameSense", "Timing", "Adaptability", "Consistency"],
        values: ["Start", "Progress", "End"],
    },

}
