const columns = [
  { name: "ID", uid: "id", sortable: true },
  { name: "GameID", uid: "game_id", sortable: true },
  { name: "NetworkID", uid: "network_id", sortable: true },
  { name: "Size", uid: "size", sortable: true },
  { name: "URL", uid: "url" },
  { name: "Status", uid: "status" },
  { name: "CreatedAt", uid: "created_at" },
  { name: "UpdatedAt", uid: "updated_at"},
  { name: "ResourceOwner", uid: "resource_owner" },
  { name: "Error", uid: "error" },
  { name: "Filestamp", uid: "filestamp" },
  { name: "Protocol", uid: "protocol" },
  { name: "NetworkProtocol", uid: "network_protocol" },
  { name: "ServerName", uid: "server_name" },
  { name: "ClientName", uid: "client_name" },
  { name: "MapName", uid: "map_name" },
  { name: "GameDirectory", uid: "game_directory" },
  { name: "Duration", uid: "length" },
  { name: "Ticks", uid: "ticks" },
  { name: "Frames", uid: "frames" },
  { name: "SignonLength", uid: "signon_length" },
];

const statusOptions = [
  { name: "Pending", uid: "pending" },
  { name: "Processing", uid: "processing" },
  { name: "Failed", uid: "failed" },
  { name: "Ready", uid: "ready" },
];


const visibilityOptions = [
  { name: "Public (Everyone)", uid: "public" },
  { name: "Private (Only me)", uid: "private" },
];

// const replayFiles = [] as typeof replayFiles2
const replayFiles = [
  {
    id: "1",
    game_id: "1",
    network_id: "1",
    size: 1,
    uri: "https://example.com",
    ["status"]: "Ready",
    error: "error",
    resource_owner: "1",
    created_at: "2021-01-01",
    updated_at: "2021-01-01",
    filestamp: "filestamp",
    protocol: 1,
    network_protocol: 1,
    server_name: "server_name",
    client_name: "client_name",
    map_name: "map_name",
    game_directory: "game_directory",
    length: "1",
    ticks: 1,
    frames: 1,
    signon_length: 1,
  },
  {
    id: "2",
    game_id: "2",
    network_id: "2",
    size: 2,
    uri: "https://example.com",
    ["status"]: "Pending",
    error: "error",
    resource_owner: "2",
    created_at: "2021-01-02",
    updated_at: "2021-01-02",
    filestamp: "filestamp",
    protocol: 2,
    network_protocol: 2,
    server_name: "server_name",
    client_name: "client_name",
    map_name: "map_name",
    game_directory: "game_directory",
    length: "2",
    ticks: 2,
    frames: 2,
    signon_length: 2,
  },
  {
    id: "3",
    game_id: "3",
    network_id: "3",
    size: 3,
    uri: "https://example.com",
    ["status"]: "Processing",
    error: "error",
    resource_owner: "3",
    created_at: "2021-01-03",
    updated_at: "2021-01-03",
    filestamp: "filestamp",
    protocol: 3,
    network_protocol: 3,
    server_name: "server_name",
    client_name: "client_name",
    map_name: "map_name",
    game_directory: "game_directory",
    length: "3",
    ticks: 3,
    frames: 3,
    signon_length: 3,
  },
  {
    id: "4",
    game_id: "4",
    network_id: "4",
    size: 4,
    uri: "https://example.com",
    ["status"]: "Failed",
    error: "error",
    resource_owner: "4",
    created_at: "2021-01-04",
    updated_at: "2021-01-04",
    filestamp: "filestamp",
    protocol: 4,
    network_protocol: 4,
    server_name: "server_name",
    client_name: "client_name",
    map_name: "map_name",
    game_directory: "game_directory",
    length: "4",
    ticks: 4,
    frames: 4,
    signon_length: 4,
  },
  {
    id: "5",
    game_id: "5",
    network_id: "5",
    size: 5,
    uri: "https://example.com",
    ["status"]: "Ready",
    error: "error",
    resource_owner: "5",
    created_at: "2021-01-05",
    updated_at: "2021-01-05",
    filestamp: "filestamp",
    protocol: 5,
    network_protocol: 5,
    server_name: "server_name",
    client_name: "client_name",
    map_name: "map_name",
    game_directory: "game_directory",
    length: "5",
    ticks: 5,
    frames: 5,
    signon_length: 5,
  },
  {
    id: "6",
    game_id: "6",
    network_id: "6",
    size: 6,
    uri: "https://example.com",
    ["status"]: "Processing",
    error: "error",
    resource_owner: "6",
    created_at: "2021-01-06",
    updated_at: "2021-01-06",
    filestamp: "filestamp",
    protocol: 6,
    network_protocol: 6,
    server_name: "server_name",
    client_name: "client_name",
    map_name: "map_name",
    game_directory: "game_directory",
    length: "6",
    ticks: 6,
    frames: 6,
    signon_length: 6,
  },
  {
    id: "7",
    game_id: "7",
    network_id: "7",
    size: 7,
    uri: "https://example.com",
    ["status"]: "Failed",
    error: "error",
    resource_owner: "7",
    created_at: "2021-01-07",
    updated_at: "2021-01-07",
    filestamp: "filestamp",
    protocol: 7,
    network_protocol: 7,
    server_name: "server_name",
    client_name: "client_name",
    map_name: "map_name",
    game_directory: "game_directory",
    length: "7",
    ticks: 7,
    frames: 7,
    signon_length: 7,
  }
]


export { columns, visibilityOptions, replayFiles, statusOptions };
